Default: &defaults
  host: "*4" # any IPv4 host
  port: 3001
  approot: "http://192.168.7.111:3001"
  copyright: Insert copyright statement here
  static: "http://192.168.7.111:3001/static"
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
